name: Currencies
version: 0.15-alpha-1
main: dansplugins.currencies.Currencies
api-version: 1.13
depend: [MedievalFactions]

commands:
  currencies:
  c:

permissions:
  currencies.help:
    default: true
  currencies.create:
    default: true
  currencies.info:
    default: true
  currencies.info.others:
    default: true
  currencies.list:
    default: true
  currencies.mint:
    default: true
  currencies.deposit:
    default: true
  currencies.withdraw:
    default: true
  currencies.desc:
    default: true
  currencies.rename:
    default: true
  currencies.retire:
    default: true
  currencies.balance:
    default: true
  currencies.balance.others:
    default: op
  currencies.config:
    default: op
  currencies.force:
    default: op
  currencies.force.retire:
    default: op