name: Currencies
version: 0.8
main: dansplugins.currencies.Currencies
api-version: 1.13
depend: [MedievalFactions]

commands:
  currencies:
  c:

permissions:
  currencies.help:
    default: true
  currencies.create:
    default: true
  currencies.info:
    default: true
  currencies.list:
    default: true
  currencies.mint:
    default: true
  currencies.balance:
    default: true
  currencies.deposit:
    default: true
  currencies.withdraw:
    default: true
  currencies.config:
    default: op