name: Currencies
version: 0.6-alpha-1
main: dansplugins.currencies.Currencies
api-version: 1.13

commands:
  currencies:
  c:

permissions:
  currencies.help:
    default: true
  currencies.create:
    default: true
  currencies.info:
    default: true
  currencies.list:
    default: true
  currencies.mint:
    default: true
  currencies.balance:
    default: true
  currencies.deposit:
    default: true
  currencies.withdraw:
    default: true