name: Currencies
version: 0.3
main: dansplugins.currencies.Currencies
api-version: 1.13

commands:
  currencies:
  c:

permissions:
  currencies.help:
    default: true
  currencies.create:
    default: true
  currencies.info:
    default: true
  currencies.list:
    default: true
  currencies.mint:
    default: true